services:
  app:
    volumes:
      - ./out:/app/out
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: testcase-generator:local
    environment:
      GITLAB_BASE_URL: ${GITLAB_BASE_URL}
      GITLAB_PROJECT_ID: ${GITLAB_PROJECT_ID}
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      LLM_PROVIDER: ${LLM_PROVIDER:-stub}        # default to stub for public demo
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
    ports:
      - "8080:8000"
    restart: unless-stopped