services:
  app:
    build:
      context: ..                      # repo root
      dockerfile: ./testcase-generator/backend/Dockerfile
    image: testcases-app:local
    environment:
      GITLAB_BASE_URL: ${GITLAB_BASE_URL}
      GITLAB_PROJECT_ID: ${GITLAB_PROJECT_ID}
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}   # or stub
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
    ports:
      - "8000:8000"
    restart: unless-stopped